### ISSUE TITLE
Add references for attacks

### ISSUE THREAD

**Issue by wielandbrendel** [google/unrestricted-adversarial-examples#30]
I really like the idea of this challenge, thanks for organising it! I am the author of the Boundary Attack and I have a small request: when I was reading "decision attack" I was naturally wondering if you are using the Boundary Attack, but I had to dive into the code to really find out. Would you mind adding the name and the reference (https://arxiv.org/abs/1712.04248) to the Readme? I guess the authors of SPAS and Spatial grid attack would also be happy about a reference ;-). Thanks!

**Comment by carlini** [comment]
Fixed in 416c373d.
