### ISSUE TITLE
Eligibility rules for team members

### ISSUE THREAD

**Issue by yi-sun** [google/unrestricted-adversarial-examples#31]
What are the eligibility rules for participants?  In particular, are family members or spouses of Google employees eligible?

**Comment by carlini** [comment]
Anyone can participate. For the warm-up, there are no restrictions.

When we figure out any prizes for the full contest, the contest organizers definitely won't be eligible for prizes. We believe (but can't commit to saying) anyone else, including google employees, will be able to get prizes.

**Comment by nottombrown** [comment]
Added to the [FAQ](https://github.com/google/unrestricted-adversarial-examples/blob/master/contest_proposal.md#additional-contest-mechanics-faq)
