### ISSUE TITLE
Cannot import bird_or_bicycle module after installation

### ISSUE THREAD

**Issue by evtimovi** [google/unrestricted-adversarial-examples#35]
After following the steps [here](
https://github.com/google/unrestricted-adversarial-examples/tree/master/bird-or-bicycle), the module `bird_or_bicycle` cannot be imported due to an `ImportError`, even though it shows up in `pip list`. 

The problem exists on two separate Ubuntu installations (one with a completely clean pip installation) and in a `pipenv` Environment.

I am not sure what the cause of this might be. I am digging around but I thought I might let you know and I’ll update if I find anything.

**Comment by nottombrown** [comment]
Very odd. Perhaps try running the commands in the `.travis.yaml` file? They run correctly in the travis test[ environment.

https://github.com/google/unrestricted-adversarial-examples/blob/master/.travis.yml#L30

**Comment by nottombrown** [comment]
It may be worthwhile to check to make sure that you are using the `pip` command that corresponds to the `python` command you are using

![image](https://user-images.githubusercontent.com/306655/45787465-61c8d480-bc2a-11e8-8781-d0b426833465.png)

**Comment by evtimovi** [comment]
Thanks!

I did check the python and pip versions before posting. No help there. And I wouldn’t be able to import other packages installed via pip, if they diverged. 

Running the commands from the yml didn’t help either.

**Comment by nottombrown** [comment]
Ok I found the issue. I had fat-fingered a refactor and renamed `bicycle` to `bicyle` everywhere 😅. Fixed here:

https://github.com/google/unrestricted-adversarial-examples/commit/b5c5211d4d25aeb597b835a50f9502904d5c20c9

**Comment by nottombrown** [comment]
Thanks for this bug report. Let me know if things work after you pull the latest version.

**Comment by nottombrown** [comment]
I'm going to close this. Feel free to reopen if you have any more issues!

**Comment by evtimovi** [comment]
This did fix it. Thanks for looking into this so quickly!

**Comment by nottombrown** [comment]
No prob. Thanks for the bug report!
