### ISSUE TITLE
Using eval_kit and meaning of 'clean' attack

### ISSUE THREAD

**Issue by sibyjackgrove** [google/unrestricted-adversarial-examples#44]
I followed the instructions for the warm-up attacks and used the API as shown below.

```
def my_custom_CNN_model(images_batch_nhwc):
    """ This mode is a valid defense based on a custom CNN. """
    predictions = model_regular.predict(images_batch_nhwc)
    return predictions.astype(np.float32)

# Evaluate the model (this will take ~10 hours on a GPU)
from unrestricted_advex import eval_kit
eval_kit.evaluate_bird_or_bicycle_model(my_custom_CNN_model)
```
Here is part of my output:
![image](https://user-images.githubusercontent.com/25213730/46035067-c7eca600-c0c7-11e8-8482-085fb212ef6d.png)

 However, I am confused by the outputs. What does 'clean' attack mean? Is this the accuracy on a normal dataset (without adversarial inputs)? Is there another method to evaluate the model on the adversarial images?

**Comment by carlini** [comment]
Yes, clean accuracy is the accuracy on the un-modified test set. The results of the other attacks will show below the clean results, in the same table.

**Comment by sibyjackgrove** [comment]
> Yes, clean accuracy is the accuracy on the un-modified test set. The results of the other attacks will show below the clean results, in the same table.

That doesn't seem to be the case when I use it. I see accuracy for only 'clean'. Please see the screenshot below:
![image](https://user-images.githubusercontent.com/25213730/46035993-0edb9b00-c0ca-11e8-8f65-fa4ba53bc60a.png)

**Comment by nottombrown** [comment]
Sorry, this was my mistake. I pushed a change that disabled the full suite of attacks. If you update to `HEAD` and re-run your command, you should see the complete grid rather than only the `clean` attack.

**Comment by sibyjackgrove** [comment]
Now it is taking 372 s/iteration. I am using the Google Colab with GPU accelerator. Please let me know if is to be expected.

![image](https://user-images.githubusercontent.com/25213730/46044933-ca5bf980-c0e1-11e8-8b22-7652fa81be53.png)

**Comment by carlini** [comment]
Yeah, unfortunately we need to improve that, see #46

**Comment by nottombrown** [comment]
Closing this issue because it is known. Perhaps we should puta  larger warning that the warm-up evaluation is very slow?

**Comment by sibyjackgrove** [comment]
> Yeah, unfortunately we need to improve that, see #46

Is there any update on this? How can I use the attack reference in #46 ?

**Comment by nottombrown** [comment]
@sibyjackgrove - How about we discuss this in issue #46?
