### ISSUE TITLE
SpatialAttack in eval_kit is sometimes extremely slow

### ISSUE THREAD

**Issue by nottombrown** [google/unrestricted-adversarial-examples#46]
This attack should take no more than 1 hour. 

I ran it for 24 hours on the `undefended_keras_resnet` and it only completed 50%.

This replaces the attack with a faster implementation that is pending in cleverhans.
https://github.com/tensorflow/cleverhans/pull/623

I've copied the attack into our repo for now, and will swap to the cleverhans version after it is released.

**Comment by nottombrown** [comment]
Cleverhans now has a canonical implementation checked in.

**Comment by nottombrown** [comment]
Using the new spatial attack, I get the following results on the keras resnet
```
+------------------------------+----------------------+----------------------+
| Attack name                  | Acc @ 80% cov        | Acc @ 100% cov       |
+------------------------------+----------------------+----------------------+
| clean                        | 1.0                  | 1.0                  |
| spatial_grid                 | 0.965                | 0.904                |
| spsa_with_random_spatial     | 0.016249999999999987 | 0.013000000000000012 |
| boundary_with_random_spatial | 0.040000000000000036 | 0.03125              |
+------------------------------+----------------------+----------------------+
```

**Comment by nottombrown** [comment]
Solved by #50

**Comment by sibyjackgrove** [comment]
I am trying out the updated attack.  It is taking 35 s/iteration. Is this to be expected?
Also, my Google Colab instance (with GPU) is dying after 4%. Usually that happens when some memory limit is reached. Does running the _spatial_grid_ attack take lot of memory?

![image](https://user-images.githubusercontent.com/25213730/46438312-2dbddb00-c723-11e8-930e-e3fe5954a530.png)

**Comment by nottombrown** [comment]
35s/iter seems correct to me. I can profile it to see if we can speed it up.

Interesting. I can profile the memory to take a look.

**Comment by sibyjackgrove** [comment]
It would be great if you could profile. I tried running it multiple times on Colab, but runtime is always running at 4%.

**Comment by nottombrown** [comment]
@sibyjackgrove - Ok take three! You can try out https://github.com/google/unrestricted-adversarial-examples/pull/52 if you'd like.

I'm not sure how many CPUs a colab env has. If it's too slow, I would recommend spinning up a GCE instance.

**Comment by sibyjackgrove** [comment]
Will you be commiting this #52 to master soon? Colab has 4 CPU's.

**Comment by nottombrown** [comment]
Yes, I plan to commit this to master after battle-testing it a bit more

**Comment by nottombrown** [comment]
Closed by #52

**Comment by sibyjackgrove** [comment]
I tried out the `eval_kit` with the new spatial_grid attack on Google Colab. It is significantly faster compared to earlier attack and I am able to complete it in 1.5 hours despite the Colab VM only having 4 CPU's.

**Comment by nottombrown** [comment]
Good to hear!
