### ISSUE TITLE
wrongly labeled examples?

### ISSUE THREAD

**Issue by cgrozea** [google/unrestricted-adversarial-examples#47]
I have noticed that in the training set the following are in the wrong folder (bird for the photo with a bike, bicycle for the photos with birds). 
Here the list:
17e90d44fda65c25.jpg
42faeb7b75b57568.jpg
8a5d9bda1c8161d0.jpg
d8829a17b7d4b512.jpg

**Comment by nottombrown** [comment]
Interesting. I'll take a look at this and resolve it by EOD

**Comment by nottombrown** [comment]
Thanks for the bug report @cgrozea ! Created a PR to resolve this issue in #49
