### ISSUE TITLE
question about the dataset

### ISSUE THREAD

**Issue by AngusG** [google/unrestricted-adversarial-examples#59]
I believe there are a few erroneous images in the training set for bird (which is significant when there are only 500 images per class).

Q 1 in Appendix ".1 Instructions given to taskers says: 

> Does this photo contain a bird, or a depiction of a bird (e.g., a toy bird, a painting of a bird, a
stuffed animal bird, a cartoon bird) anywhere in the image?

However, point 4 and the italicized text below suggest that paintings/depictions are not allowed:
 
> (It is okay if the object is a **photorealistic** rendering of a bird/bicycle.) .. , is not
truncated, is not occluded, and is **not a depiction** of any sort.

In any case, I do not believe this black and white sketch from the bird training set should be included:

![2e8cd9f60546ac55](https://user-images.githubusercontent.com/5000421/48081465-25dbd580-e1be-11e8-9053-47d6b5517bad.jpg)

There's also:

![954c63e11aa1232e](https://user-images.githubusercontent.com/5000421/48082599-085c3b00-e1c1-11e8-9815-1b15129abfa2.jpg)

And this image (also from the bird training set) is of a moth:
![6b3797dec5bea3c7](https://user-images.githubusercontent.com/5000421/48081532-4441d100-e1be-11e8-9720-79d29ee21d30.jpg)

**Comment by AngusG** [comment]
Also, there are several truncated bird images where either only the bird's head is visible, or the head is missing. Instruction 4 says:

> 4. This bird/bicycle is complete and not truncated. It does not go outside of the image at all

But it's unlikely taskers would make it this far since I would have answered "Definitely yes" to Q1 for all of these samples. I don't see how representations learned on bird heads can be expected to generalize to birds at an arbitrary distance from the camera, esp when there is no requirement that the bird be facing the camera.

![e77595104d2f62a4](https://user-images.githubusercontent.com/5000421/48082283-38efa500-e1c0-11e8-9695-d309dee3def7.jpg)
![6a8cf5ae66f3f4b2](https://user-images.githubusercontent.com/5000421/48082323-545ab000-e1c0-11e8-9b32-a0b51fe092b0.jpg)
![3b5b81359c0f337c](https://user-images.githubusercontent.com/5000421/48082325-558bdd00-e1c0-11e8-9891-8a3a01080953.jpg)

This bird has no head:
![3f9b4b2ad5991d96](https://user-images.githubusercontent.com/5000421/48082736-5a9d5c00-e1c1-11e8-8287-397fadc982cb.jpg)

**Comment by nottombrown** [comment]
Thanks for bringing this to our attention @AngusG. I agree that those datapoints are erroneous and will investigate how they got into the training set.

**Comment by nottombrown** [comment]
Resolved by https://github.com/google/unrestricted-adversarial-examples/pull/60 

Thanks again for noticing this @AngusG

**Comment by AngusG** [comment]
Thanks for dealing with this so quickly, glad to know I interpreted the data spec correctly. I noticed this ended up affecting even more images which were moved to the `extras` split. Do you have a spec or intended use case for the `extras` in mind? For instance, I can see some kind of unsupervised pre-training based on the moth image still being useful for detecting birds since it's a natural scene where the object of focus has a similar shape and context as a bird image.

**Comment by nottombrown** [comment]
Exactly. The idea behind extras is that it would be useful for training
classifiers even though it is less pristine than the IID train and test
data.

The SVHN dataset follows this convention as well.
