### ISSUE TITLE
Google Colab Could not find a version that satisfies the requirement playwright

### ISSUE THREAD

**Issue by idilkylmz** [google/unrestricted-adversarial-examples#84]
Hi I am trying to install tiktok api for google colab but I get this error, how can I fix this?

!pip install TikTokApi
Collecting TikTokApi
  Using cached https://files.pythonhosted.org/packages/c3/83/6c2c1d36fbe85216ce469f409b98a3cd4a0732c2fdcceb345f8eb5d8e2f8/TikTokApi-3.8.9.tar.gz
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from TikTokApi) (2.23.0)
ERROR: Could not find a version that satisfies the requirement playwright (from TikTokApi) (from versions: none)
ERROR: No matching distribution found for playwright (from TikTokApi)

**Comment by carlini** [comment]
Is this related to this project?
